# Generated by Django 4.2.30 on 2026-05-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_approve_existing_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingprofile',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
