"""
SHELL — Generic listing platform wiring.
========================================
You do NOT edit this file when cloning for jobs or cars.
Change only: backend/features/listing/schema.py
             frontend/src/app/core/listing.schema.ts
"""

FEATURE_APPS = [
    "features.listing",
]

FEATURE_API_INCLUDES = [
    "features.listing.urls",
]
